apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kafka-ui-oci-repo
  namespace: infra
spec:
  interval: 1m  # Polling interval for checking for updates
  url: oci://gitlab.example.com:5000/okd/apps/deployments  # URL of your Helm repository
  type: "oci"
  provider: generic
  secretRef:
    name: ghcr-auth
    # namespace: flux-system