apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka-ui-helm-release
  namespace: infra
spec:
  interval: 1m
  chart:
    spec:
      chart: kafka-ui
      version: '0.7.5'
      sourceRef:
        kind: HelmRepository
        name: kafka-ui-helm-repo
        namespace: infra
      interval: 1m
  serviceAccountName: flux
  valuesFrom:
  - kind: ConfigMap
    name: kafka-ui-values
    valuesKey: values.yaml